create table
  public.post_likes (
    id bigint generated by default as identity,
    uid uuid null default auth.uid (),
    post_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint post_likes_pkey primary key (id),
    constraint post_likes_post_id_fkey foreign key (post_id) references posts (id),
    constraint post_likes_uid_fkey foreign key (uid) references users (uid)
  ) tablespace pg_default;