CREATE EXTENSION IF NOT EXISTS moddatetime
	SCHEMA "extensions";

create table
  public.posts (
    id bigint generated by default as identity,
    content character varying null,
    type character varying null,
    source character varying null,
    uid uuid null default auth.uid (),
    created_at timestamp with time zone not null default now(),
    active boolean null default true,
    modified_at timestamp with time zone null,
    constraint thoughts_pkey primary key (id),
    constraint posts_id_key unique (id),
    constraint posts_uid_fkey foreign key (uid) references users (uid)
  ) tablespace pg_default;

create trigger handle_updated_at before
update on posts for each row
execute function moddatetime ('modified_at');